# Generated by Django 2.2.5 on 2019-10-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191003_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='accounts/user.png', upload_to='accounts/'),
        ),
    ]
