# Generated by Django 2.2.5 on 2019-09-29 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('News', 'News'), ('Tech', 'Tech'), ('Health', 'Health'), ('Music', 'Music'), ('Food', 'Food'), ('Games', 'Games'), ('Entertainment', 'Entertainment'), ('Environment', 'Environment')], max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 9, 29, 14, 54, 50, 998906))),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='forum')),
            ],
        ),
    ]
