# Generated by Django 2.2.5 on 2019-10-03 03:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('News', 'News'), ('Tech', 'Tech'), ('Health', 'Health'), ('Music', 'Music'), ('Food', 'Food'), ('Games', 'Games'), ('Entertainment', 'Entertainment'), ('Environment', 'Environment')], max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 10, 3, 9, 6, 49, 834523))),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, default='forum/user.png', upload_to='forum/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
