# Generated by Django 2.2.5 on 2019-10-24 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20191024_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='report',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 15, 56, 55, 931066)),
        ),
    ]
