# Generated by Django 2.2.5 on 2019-10-24 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20191024_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 17, 14, 16, 261907)),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='forum/user.png', upload_to='forum/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='report',
            field=models.IntegerField(default=1, max_length=3),
        ),
    ]
